sudo: required
dist: trusty
language: csharp

# Build the project
solution: Unboxed.sln

# Run deployment script
after_success: "[[ $TRAVIS_REPO_SLUG == OxideMod/Unboxed ]] && [[ $TRAVIS_PULL_REQUEST == false ]] && [[ $TRAVIS_BRANCH == master ]] && ./deploy.sh"

notifications:
  email: false
  slack:
    rooms:
      secure: "TMzZM9Ff3fHQ+o1f26N4QQ7MbGG82wQdzfeLJGJZie3aKHPbGYnHoff+6sUuq6SaL7nzXPy+GNoYP1uwmg9uNaTLTDTj9C1quqmaqLu6cBTc8sBtEK4/crP8m1f/r7b9xWsCMcqbQGZmQsJqHyi7pngcUTVjG3sGK8BjMSs3tk8JVTNM0sOGOE5s2LkPgYfRAytJbjSmYYVfPoVeEEDP4RuOgDwMS+OlMLsCEPw8ypovgez04r5Fs+OIVX4K37M2EIgfbH388y2jmaqJRSUD9+VU7gEU4rw5eNFYk6WZ4JhEsWQnftLJGBjezwOYLdqMi+llyxwF01DXM4eHATsbkHqN+apFi0wONzOMJBLxXcnVhMqn/+Ud9ecJ5Tvlp7ulB4HKsqfXOUKXn8i/5xYfmoKKg9r3Jw0cPVxkau4D7uqm+NytvsF3sspPZSQQQkWmJu0WTjiyvVGT16RjcxjtqvGH5b9O96BlL1/8EtYApjSdM+ifFIoZmHNjW2DfkR+cx5GZaCSGE3dkacvDRaJZuIwpFVrv/WmeEYdHHI3lmCO85/THqNQLcbfVOljAIMz639V8E2QeVpnC7IkvWx/MfAI8X83I6BAqpajubmtXaA58BatqeBuWz8XmVc9eKjNBe7FdSLs5WMxyP8whwkzHC5TbxjFUJmPp/NQQp/I8r2Q="

env:
  global:
    - secure: "bBfhulPJ45FOQETTMkcl0Johg0y3SdHqNOsyiK6sPj7hzdBiTsdeg3v/7jJkSZosAZqYjyKBU+wG4vBOTe7Qh3QAKQY9zKBC6WE4Qlo6bp3BfBa30wVdRSo0yC8z46GQZ0sfzHV46hIaSYZDXHBD37Vptq63ftu/X00a5PqOaBus5FPveoOXdLuZHKb2WvOXFHFbc6xMuvx16SammSPZ75rU9WsR3z0Zc20UCROTVaM+nVOW5VPR6SjFHdSgNJ3Y5IYzCNJvxXKCI/h4LxiCa8OrgRsF3reeUegUryhWSdAHsEqXpu7l617rlRN8ckDJRNugCtdRuGhoLH0AWpzpXyvNcQOz89Pce5q0ZR2zA+228IRC92udZxLsdsBCbpTFPF02Z0PQrTLV33i6VSbzK6G80KQAZ2zH/m9T75yDAEv25/wLIRhvC1iQ8c1DEjhBywUej6uD7+gp8TsMQk9x/G1BqUPD3Pab4bE8sDKO0eZKchfos7ZQdomkHBEd5Bq+YXz5lRsav1XCnqWUkkPcsordkevyVtvWnf1ytc2PYU11eHzmHYF0xeJqRuP/Y18K2KwhSBqYWfznlER+iwpmDOdIY498DgpZ+bZ+TcUhhnXPT4xPT3GBemOV3sYZCK7kB8Zp6lWwHDNYfOyiduiI6yjuy2AWOOxcQ4VbY5pMvvE="
